---
# vars:
#   admin_user: "postgres"
#   admin_group: "{{ admin_user }}"
#   [host: "{{ db_host }}"]
#   database: "{{ db_name }}"
#   user: "{{ db_user }}"
#   query_file: "query.sql.j2"

- name: set remote query file value
  set_fact:
    remote_query_file: "~/{{ query_file | basename | regex_replace('.j2', '') }}"

- name: copy sql file to the server
  template:
    src: "{{ query_file }}"
    dest: "{{ remote_query_file }}"
    owner: "{{ admin_user }}"
    group: "{{ admin_group | default(admin_user) }}"
    mode: 0644

- name: execute query from file
  shell: "psql -U {{ user }} {% if host is defined %}-h {{ host }}{% endif %} -d {{ database }} < {{ remote_query_file }}"
  register: result

- name: remove the sql file from the server
  file:
    path: "{{ remote_query_file }}"
    state: absent
  when: not postgres_util_debugging

- name: display result
  debug:
    var: result.stdout_lines
